-- liquibase formatted sql

-- changeset script:1
-- comment: Creation table tipo_de_pago

create table tipo_de_pago (
    id_tipo_de_pago integer generated by default as identity,
    tipo_pago varchar(255),
    active boolean,
    date_creation timestamp,
    date_modification timestamp,
    user_creation varchar(50),
    user_modification varchar(50),
    primary key (id_tipo_de_pago)
);

-- changeset script:2
-- comment: Creation table detalles
create table detalles (
    id_detalle integer generated by default as identity,
    cantidad integer,
    precio_unitario integer,
    id_factura_fk integer,
    id_producto_fk integer,
    active boolean,
    date_creation timestamp,
    date_modification timestamp,
    user_creation varchar(50),
    user_modification varchar(50),
    primary key (id_detalle)
);

-- changeset script:3
-- comment: Creation table facturas
create table facturas (
    id_factura integer generated by default as identity,
    active boolean,
    date_creation timestamp,
    date_modification timestamp,
    user_creation varchar(50),
    user_modification varchar(50),
    iva integer, descuento integer,
    documento_client varchar(255),
    fecha timestamp,
    nombre_cliente varchar(255),
    numero_factura integer,
    subtotal integer,
    total integer,
    total_descuento integer,
    total_impuesto integer,
    id_tipo_de_pago_fk integer,
    primary key (id_factura)
);

-- changeset script:4
-- comment: Creation table productos
create table productos (
    id_producto integer generated by default as identity,
    producto varchar(255),
    active boolean,
    date_creation timestamp,
    date_modification timestamp,
    user_creation varchar(50),
    user_modification varchar(50),
    primary key (id_producto)
 );

-- changeset script:5
-- comment: Creation table tipo_de_pago
INSERT INTO tipo_de_pago(tipo_pago, active)	VALUES
    ( 'Electronico', true),
	( 'Efectivo', true);

-- changeset script:6
-- comment: Creation table facturas
INSERT INTO facturas(numero_factura, fecha, id_tipo_de_pago_fk, documento_client, nombre_cliente, subtotal, descuento, IVA, total_descuento, total_impuesto, total, active)	VALUES
    ( 1001, null, 1, 951357852, 'Alverto Castro', 10000, 190, 19, 190, 19, 15000, true ),
	( 1002, null, 1, 951357852, 'Alverto Quintana', 10000, 190, 19, 190, 19, 15000, true );

-- changeset script:7
-- comment: Creation table detalles
INSERT INTO detalles(id_factura_fk, id_producto_fk, cantidad, precio_unitario, active)	VALUES
    ( 1, 1, 8, 200, true),
	( 1, 1, 10, 500, true);

-- changeset script:8
-- comment: Creation table productos
INSERT INTO productos(producto, active)	VALUES
    ( 'Arroz', true),
	( 'Sal', true);
